services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh start_local.sh
    ports:
      - "8000:8000"
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    depends_on:
      - postgres
      - redis
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A feature_library flower --port=5555
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feature_library
    ports:
      - "5432:5432"
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A feature_library worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    depends_on:
      - redis
      - postgres
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A feature_library beat --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    depends_on:
      - redis
