services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh start_local.sh
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A feature_library flower --port=5555
    ports:
      - "5555:5555"
  redis:
    image: redis:latest
    ports:
      - "63799:63799"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feature_library
    ports:
      - "5432:5432"
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A feature_library worker --loglevel=info
    depends_on:
      - redis
      - postgres
